version: 1.0.{build}
image: Visual Studio 2015
environment:
  matrix:
  - PYTHON: C:\Miniconda36-x64
  - PYTHON: C:\Miniconda35-x64
  - PYTHON: C:\Miniconda36
  - PYTHON: C:\Miniconda35
max_jobs: 4
install:
- cmd: >-
    ECHO %APPVEYOR_REPO_TAG%

    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python --version

    conda install -y xerces-c setuptools

    pip install -r C:\projects\pye57\requirements.txt

    git submodule update --init --recursive
build_script:
- cmd: >-
    python.exe setup.py build_ext -i
test_script:
- cmd: >-
    cd C:\projects\pye57

    python setup.py test
after_test:
  - IF "%APPVEYOR_REPO_TAG%" == "true" (pip install wheel twine)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (python.exe setup.py bdist_wheel)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (dir dist)
on_success:
  - IF "%APPVEYOR_REPO_TAG%" == "true" (twine upload --skip-existing dist/*.whl)